const fs = require("fs");
var L = [];
L.push("import { Component, signal, inject } from '@angular/core';");
L.push("import { RouterOutlet, RouterLink, RouterLinkActive, Router } from '@angular/router';");
L.push("import { AuthService } from '../../core/services/auth.service';");
L.push("import { CartService } from '../../core/services/cart.service';");
L.push("import { Toast } from '../../shared/components/toast/toast';");
L.push("");
L.push("@Component({");
L.push("  selector: 'app-layout',");
L.push("  standalone: true,");
L.push("  imports: [RouterOutlet, RouterLink, RouterLinkActive, Toast],");
L.push('  template: \x60');
L.push('    <div class="layout">');
L.push('      <aside class="sidebar" [class.collapsed]="sidebarCollapsed()">');
L.push('        <div class="sidebar-header">');
L.push('          <div class="logo">');
L.push('            <span class="logo-icon">\u{1F4B3}</span>');
L.push('            @if (!sidebarCollapsed()) {');
L.push('              <span class="logo-text">\u0646\u0642\u0637\u0629 \u0627\u0644\u0628\u064A\u0639</span>');
L.push('            }');
L.push('          </div>');
L.push('          <button class="sidebar-toggle" (click)="toggleSidebar()">');
L.push('            {{ sidebarCollapsed() ? "\u2630" : "\u2715" }}');
L.push('          </button>');
L.push('        </div>');
L.push('        <nav class="sidebar-nav">');
L.push('          @for (item of navItems; track item.route) {');
L.push('            <a class="nav-item" [routerLink]="item.route" routerLinkActive="active" [routerLinkActiveOptions]="{exact: item.exact}">');
L.push('              <span class="nav-icon">{{ item.icon }}</span>');
L.push('              @if (!sidebarCollapsed()) {');
L.push('                <span class="nav-label">{{ item.label }}</span>');
L.push('              }');
L.push('              @if (item.route === "/pos" \&\& cartService.itemCount() > 0) {');
L.push('                <span class="nav-badge">{{ cartService.itemCount() }}</span>');
L.push('              }');
L.push('            </a>');
L.push('          }');
L.push('        </nav>');
L.push('        <div class="sidebar-footer">');
L.push('          @if (!sidebarCollapsed()) {');
L.push('            <div class="user-info">');
L.push('              <span class="user-name">{{ authService.currentUser()?.displayName }}</span>');
L.push('              <span class="user-role">{{ authService.currentUser()?.role === "admin" ? "\u0645\u062F\u064A\u0631" : "\u0643\u0627\u0634\u064A\u0631" }}</span>');
L.push('            </div>');
L.push('          }');
L.push('          <button class="nav-item logout-btn" (click)="logout()">');
L.push('            <span class="nav-icon">\u{1F6AA}</span>');
L.push('            @if (!sidebarCollapsed()) {');
L.push('              <span class="nav-label">\u062A\u0633\u062C\u064A\u0644 \u0627\u0644\u062E\u0631\u0648\u062C</span>');
L.push('            }');
L.push('          </button>');
L.push('        </div>');
L.push('      </aside>');
L.push('      <main class="main-content"><router-outlet /></main>');
L.push('      <nav class="mobile-nav">');
L.push('        @for (item of mobileNavItems; track item.route) {');
L.push('          <a class="mobile-nav-item" [routerLink]="item.route" routerLinkActive="active" [routerLinkActiveOptions]="{exact: item.exact}">');
L.push('            <span class="mobile-nav-icon">{{ item.icon }}</span>');
L.push('            <span class="mobile-nav-label">{{ item.label }}</span>');
L.push('            @if (item.route === "/pos" \&\& cartService.itemCount() > 0) {');
L.push('              <span class="mobile-badge">{{ cartService.itemCount() }}</span>');
L.push('            }');
L.push('          </a>');
L.push('        }');
L.push('        <button class="mobile-nav-item" (click)="logout()"><span class="mobile-nav-icon">\u{1F6AA}</span><span class="mobile-nav-label">\u062E\u0631\u0648\u062C</span></button>');
L.push('      </nav>');
L.push('      <app-toast />');
L.push('    </div>');
L.push('  \x60,');
L.push('  styles: [\x60');
L.push(".layout{display:flex;min-height:100vh}");
L.push(".sidebar{width:250px;background:#111827;color:white;display:flex;flex-direction:column;position:fixed;right:0;top:0;bottom:0;z-index:100;transition:width .3s ease}");
L.push(".sidebar.collapsed{width:70px}");
L.push(".sidebar-header{display:flex;align-items:center;justify-content:space-between;padding:1.25rem 1rem;border-bottom:1px solid rgba(255,255,255,.1)}");
L.push(".logo{display:flex;align-items:center;gap:.75rem}");
L.push(".logo-icon{font-size:1.5rem}");
L.push(".logo-text{font-size:1.1rem;font-weight:700;white-space:nowrap}");
L.push(".sidebar-toggle{background:none;border:none;color:white;font-size:1.2rem;cursor:pointer;padding:.25rem;border-radius:6px;opacity:.7}");
L.push(".sidebar-toggle:hover{opacity:1;background:rgba(255,255,255,.1)}");
L.push(".sidebar-nav{flex:1;padding:.75rem 0;overflow-y:auto}");
L.push(".nav-item{display:flex;align-items:center;gap:.75rem;padding:.75rem 1rem;color:rgba(255,255,255,.7);text-decoration:none;font-family:Cairo,sans-serif;font-size:.9rem;cursor:pointer;transition:all .2s;border:none;background:none;width:100%;text-align:right}");
L.push(".nav-item:hover{background:rgba(255,255,255,.1);color:white}");
L.push(".nav-item.active{background:rgba(59,130,246,.2);color:#60a5fa;border-right:3px solid #3b82f6}");
L.push(".sidebar.collapsed .nav-item{justify-content:center;padding:.75rem}");
L.push(".nav-icon{font-size:1.2rem;min-width:1.5rem;text-align:center}");
L.push(".nav-label{white-space:nowrap}");
L.push(".nav-badge{background:#ef4444;color:white;border-radius:10px;padding:.1rem .45rem;font-size:.7rem;font-weight:700;margin-right:auto}");
L.push(".sidebar-footer{padding:.75rem 0;border-top:1px solid rgba(255,255,255,.1)}");
L.push(".user-info{padding:.5rem 1rem;display:flex;flex-direction:column}");
