services:
  - type: web
    name: freebuff-pos
    env: docker
    region: KSA
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
